const tracks = [
  {
    id: 0,
    name: 'Guilt',
    author: 'Nero',
    album: 'Welcome Reality',
    isliked: false,
    time: '4:44',
    genre: 'Рок',
  },
  {
    id: 1,
    name: 'Elektro',
    author: 'Dynoro, Outwork, Mr. Gee',
    album: 'Elektro',
    isliked: false,
    time: '2:22',
    genre: 'Хип-хоп',
  },
  {
    id: 2,
    name: 'I’m Fire',
    author: 'Ali Bakgor',
    album: 'I’m Fire',
    isliked: false,
    time: '2:22',
    genre: 'Поп-музыка',
  },
  {
    id: 3,
    name: 'Non Stop',
    remix: 'Remix',
    author: 'Стоункат, Psychopath',
    album: 'Non Stop',
    isliked: false,
    time: '4:12',
    genre: 'Техно',
  },
  {
    id: 4,
    name: 'Run Run',
    remix: 'feat. AR/CO',
    author: 'Jaded, Will Clarke, AR/CO',
    album: 'Run Run',
    isliked: false,
    time: '2:54',
    genre: 'Инди',
  },
  {
    id: 5,
    name: 'Eyes on Fire',
    remix: 'Zeds Dead Remix',
    author: 'Blue Foundation, Zeds Dead',
    album: 'Eyes on Fire',
    isliked: false,
    time: '5:20',
    genre: 'Рок',
  },
  {
    id: 6,
    name: 'Mucho Bien',
    remix: 'Hi Profile Remix',
    author: 'HYBIT, Mr. Black, Offer Nissim, Hi Profile',
    album: 'Mucho Bien',
    isliked: false,
    time: '3:41',
    genre: 'Поп-музыка',
  },
  {
    id: 7,
    name: 'Knives n Cherries',
    author: 'minthaze',
    album: 'Captivating',
    isliked: false,
    time: '1:48',
    genre: 'Техно',
  },
  {
    id: 8,
    name: 'How Deep Is Your Love',
    author: 'Calvin Harris, Disciples',
    album: 'How Deep Is Your Love',
    isliked: false,
    time: '3:32',
    genre: 'Рок',
  },
  {
    id: 9,
    name: 'Morena',
    author: 'Tom Boxer',
    album: 'Soundz Made in Romania',
    isliked: false,
    time: '3:36',
    genre: 'Инди',
  },
]
const playLists = [
  {
    id: 1,
    name: 'Плейлист дня',
    src: '/img/playlist01.png',
  },
  {
    id: 2,
    name: '100 танцевальных хитов',
    src: '/img/playlist02.png',
  },
  {
    id: 3,
    name: 'Инди-заряд',
    src: '/img/playlist03.png',
  },
]

export { tracks }
export { playLists }
